//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegeditWinUI.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RegeditWinUI.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registry Editor\nVersion 1.0\n\nA WinUI 3 implementation of the Windows Registry Editor..
        /// </summary>
        internal static string AboutText {
            get {
                return ResourceManager.GetString("AboutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registry Editor.
        /// </summary>
        internal static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string ButtonCancel {
            get {
                return ResourceManager.GetString("ButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Next.
        /// </summary>
        internal static string ButtonFindNext {
            get {
                return ResourceManager.GetString("ButtonFindNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string ButtonOK {
            get {
                return ResourceManager.GetString("ButtonOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        internal static string ColumnData {
            get {
                return ResourceManager.GetString("ColumnData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string ColumnName {
            get {
                return ResourceManager.GetString("ColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string ColumnType {
            get {
                return ResourceManager.GetString("ColumnType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computer.
        /// </summary>
        internal static string Computer {
            get {
                return ResourceManager.GetString("Computer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Delete.
        /// </summary>
        internal static string ConfirmDelete {
            get {
                return ResourceManager.GetString("ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to permanently delete this key and all of its subkeys?.
        /// </summary>
        internal static string ConfirmDeleteKey {
            get {
                return ResourceManager.GetString("ConfirmDeleteKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting certain registry values could cause system instability. Are you sure you want to permanently delete this value?.
        /// </summary>
        internal static string ConfirmDeleteValue {
            get {
                return ResourceManager.GetString("ConfirmDeleteValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to Favorites.
        /// </summary>
        internal static string DialogAddFavorite {
            get {
                return ResourceManager.GetString("DialogAddFavorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Binary Value.
        /// </summary>
        internal static string DialogEditBinary {
            get {
                return ResourceManager.GetString("DialogEditBinary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit DWORD (32-bit) Value.
        /// </summary>
        internal static string DialogEditDWORD {
            get {
                return ResourceManager.GetString("DialogEditDWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Expandable String.
        /// </summary>
        internal static string DialogEditExpandString {
            get {
                return ResourceManager.GetString("DialogEditExpandString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Multi-String.
        /// </summary>
        internal static string DialogEditMultiString {
            get {
                return ResourceManager.GetString("DialogEditMultiString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit QWORD (64-bit) Value.
        /// </summary>
        internal static string DialogEditQWORD {
            get {
                return ResourceManager.GetString("DialogEditQWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit String.
        /// </summary>
        internal static string DialogEditString {
            get {
                return ResourceManager.GetString("DialogEditString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Registry File.
        /// </summary>
        internal static string DialogExport {
            get {
                return ResourceManager.GetString("DialogExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find.
        /// </summary>
        internal static string DialogFind {
            get {
                return ResourceManager.GetString("DialogFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Favorites.
        /// </summary>
        internal static string DialogRemoveFavorite {
            get {
                return ResourceManager.GetString("DialogRemoveFavorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access is denied..
        /// </summary>
        internal static string ErrorAccessDenied {
            get {
                return ResourceManager.GetString("ErrorAccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create key: error writing to the registry..
        /// </summary>
        internal static string ErrorCannotCreate {
            get {
                return ResourceManager.GetString("ErrorCannotCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot rename: the specified key name already exists..
        /// </summary>
        internal static string ErrorCannotRename {
            get {
                return ResourceManager.GetString("ErrorCannotRename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error importing file: {0}.
        /// </summary>
        internal static string ImportError {
            get {
                return ResourceManager.GetString("ImportError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file was successfully imported..
        /// </summary>
        internal static string ImportSuccess {
            get {
                return ResourceManager.GetString("ImportSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base.
        /// </summary>
        internal static string LabelBase {
            get {
                return ResourceManager.GetString("LabelBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        internal static string LabelData {
            get {
                return ResourceManager.GetString("LabelData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decimal.
        /// </summary>
        internal static string LabelDecimal {
            get {
                return ResourceManager.GetString("LabelDecimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string LabelExportAll {
            get {
                return ResourceManager.GetString("LabelExportAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export range.
        /// </summary>
        internal static string LabelExportRange {
            get {
                return ResourceManager.GetString("LabelExportRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected branch.
        /// </summary>
        internal static string LabelExportSelectedBranch {
            get {
                return ResourceManager.GetString("LabelExportSelectedBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorite name:.
        /// </summary>
        internal static string LabelFavoriteName {
            get {
                return ResourceManager.GetString("LabelFavoriteName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find what:.
        /// </summary>
        internal static string LabelFindWhat {
            get {
                return ResourceManager.GetString("LabelFindWhat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hexadecimal.
        /// </summary>
        internal static string LabelHexadecimal {
            get {
                return ResourceManager.GetString("LabelHexadecimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keys.
        /// </summary>
        internal static string LabelKeys {
            get {
                return ResourceManager.GetString("LabelKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Look at.
        /// </summary>
        internal static string LabelLookAt {
            get {
                return ResourceManager.GetString("LabelLookAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match whole string only.
        /// </summary>
        internal static string LabelMatchWholeString {
            get {
                return ResourceManager.GetString("LabelMatchWholeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value data:.
        /// </summary>
        internal static string LabelValueData {
            get {
                return ResourceManager.GetString("LabelValueData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value name:.
        /// </summary>
        internal static string LabelValueName {
            get {
                return ResourceManager.GetString("LabelValueName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Values.
        /// </summary>
        internal static string LabelValues {
            get {
                return ResourceManager.GetString("LabelValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Registry Editor.
        /// </summary>
        internal static string MenuAbout {
            get {
                return ResourceManager.GetString("MenuAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Bar.
        /// </summary>
        internal static string MenuAddressBar {
            get {
                return ResourceManager.GetString("MenuAddressBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to Favorites....
        /// </summary>
        internal static string MenuAddToFavorites {
            get {
                return ResourceManager.GetString("MenuAddToFavorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect Network Registry....
        /// </summary>
        internal static string MenuConnectNetworkRegistry {
            get {
                return ResourceManager.GetString("MenuConnectNetworkRegistry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Key Name.
        /// </summary>
        internal static string MenuCopyKeyName {
            get {
                return ResourceManager.GetString("MenuCopyKeyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string MenuDelete {
            get {
                return ResourceManager.GetString("MenuDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect Network Registry....
        /// </summary>
        internal static string MenuDisconnectNetworkRegistry {
            get {
                return ResourceManager.GetString("MenuDisconnectNetworkRegistry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string MenuEdit {
            get {
                return ResourceManager.GetString("MenuEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string MenuExit {
            get {
                return ResourceManager.GetString("MenuExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export....
        /// </summary>
        internal static string MenuExport {
            get {
                return ResourceManager.GetString("MenuExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorites.
        /// </summary>
        internal static string MenuFavorites {
            get {
                return ResourceManager.GetString("MenuFavorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string MenuFile {
            get {
                return ResourceManager.GetString("MenuFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find....
        /// </summary>
        internal static string MenuFind {
            get {
                return ResourceManager.GetString("MenuFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Next.
        /// </summary>
        internal static string MenuFindNext {
            get {
                return ResourceManager.GetString("MenuFindNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string MenuHelp {
            get {
                return ResourceManager.GetString("MenuHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import....
        /// </summary>
        internal static string MenuImport {
            get {
                return ResourceManager.GetString("MenuImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Hive....
        /// </summary>
        internal static string MenuLoadHive {
            get {
                return ResourceManager.GetString("MenuLoadHive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify....
        /// </summary>
        internal static string MenuModify {
            get {
                return ResourceManager.GetString("MenuModify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify Binary Data....
        /// </summary>
        internal static string MenuModifyBinary {
            get {
                return ResourceManager.GetString("MenuModifyBinary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        internal static string MenuNew {
            get {
                return ResourceManager.GetString("MenuNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binary Value.
        /// </summary>
        internal static string MenuNewBinaryValue {
            get {
                return ResourceManager.GetString("MenuNewBinaryValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DWORD (32-bit) Value.
        /// </summary>
        internal static string MenuNewDWORDValue {
            get {
                return ResourceManager.GetString("MenuNewDWORDValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expandable String Value.
        /// </summary>
        internal static string MenuNewExpandStringValue {
            get {
                return ResourceManager.GetString("MenuNewExpandStringValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key.
        /// </summary>
        internal static string MenuNewKey {
            get {
                return ResourceManager.GetString("MenuNewKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multi-String Value.
        /// </summary>
        internal static string MenuNewMultiStringValue {
            get {
                return ResourceManager.GetString("MenuNewMultiStringValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QWORD (64-bit) Value.
        /// </summary>
        internal static string MenuNewQWORDValue {
            get {
                return ResourceManager.GetString("MenuNewQWORDValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String Value.
        /// </summary>
        internal static string MenuNewStringValue {
            get {
                return ResourceManager.GetString("MenuNewStringValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permissions....
        /// </summary>
        internal static string MenuPermissions {
            get {
                return ResourceManager.GetString("MenuPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print....
        /// </summary>
        internal static string MenuPrint {
            get {
                return ResourceManager.GetString("MenuPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string MenuRefresh {
            get {
                return ResourceManager.GetString("MenuRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Favorite....
        /// </summary>
        internal static string MenuRemoveFavorite {
            get {
                return ResourceManager.GetString("MenuRemoveFavorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        internal static string MenuRename {
            get {
                return ResourceManager.GetString("MenuRename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status Bar.
        /// </summary>
        internal static string MenuStatusBar {
            get {
                return ResourceManager.GetString("MenuStatusBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unload Hive....
        /// </summary>
        internal static string MenuUnloadHive {
            get {
                return ResourceManager.GetString("MenuUnloadHive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        internal static string MenuView {
            get {
                return ResourceManager.GetString("MenuView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This feature is not yet implemented..
        /// </summary>
        internal static string NotImplemented {
            get {
                return ResourceManager.GetString("NotImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished searching through the registry..
        /// </summary>
        internal static string SearchComplete {
            get {
                return ResourceManager.GetString("SearchComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching....
        /// </summary>
        internal static string Searching {
            get {
                return ResourceManager.GetString("Searching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registry Editor.
        /// </summary>
        internal static string SearchTitle {
            get {
                return ResourceManager.GetString("SearchTitle", resourceCulture);
            }
        }
    }
}
