using Duct.AppTests.Host.SelfTest.Fixtures;

namespace Duct.AppTests.Host.SelfTest;

/// <summary>
/// Maps fixture names to their self-test implementations (the ones with assertions).
/// </summary>
internal static class SelfTestFixtureRegistry
{
    public static readonly string[] AllFixtures =
    [
        "ErrorBoundary_CatchesRenderError",
        "ErrorBoundary_Recovery",
        "Reconciler_MountText",
        "Reconciler_UpdateText",
        "Reconciler_AddRemoveChildren",
        "Reconciler_ComponentRerender",
        "Reconciler_KeyedList",
        "Reconciler_GridDynamicChildCount",
        "Reconciler_AllLayoutsDynamicChildCount",
        "FlexLayout_RowDistribution",
        "FlexLayout_ColumnWrap",
        "Grid_RowColumnLayout",
        "GridVsFlex_StarSizing",
        "Flex_NestedRowInColumn",
        "Flex_NestedColumnInRow",
        "Flex_NestedDeep",
        "Flex_InsideGrid",
        "Flex_InsideBorder",
        "Flex_InsideVStack",
        "Flex_InsideScrollView",
        "Flex_ScrollViewInsideFlex",
        "Flex_ColumnGrow",
        "Flex_MixedGrowFixed",
        "Flex_WithGaps",
        "Flex_WithPadding",
        "Flex_CrossAxisTextHeight",
        "Flex_GridInsideFlex",
        "Flex_WithChildMargins",
        "Flex_JustifySpaceBetween",
        "Flex_LayoutCycleInGridStar",
        "Flex_LayoutCycleNestedDeep",
        "Flex_LayoutCycleAutoText",
        "Flex_LayoutCycleSizeMismatch",
        "DynamicList_GrowShrink",
        "ConditionalRendering_Toggle",
        "Markdown_HeadingsAndFormatting",
        "Markdown_CodeBlockAndLinks",
        "MonacoEditor_Mounts",
        "D3_LineChart",
        "D3_BarChart",
        "D3_PieChart",
        "ListView_TypedRendering",
        "Navigation_TabSwitching",
        "Navigation_NavHostRendersInitial",
        "Navigation_NavHostContentSwap",
        "Navigation_NavHostGoBack",
        "Navigation_NavHostLifecycleOrder",
        "Navigation_NavHostNested",
        "Observable_UseObservable_Rerender",
        "Observable_UseObservable_ExternalMutation",
        "Observable_UseObservableProperty_FineGrained",
        "Observable_UseCollection_ListUpdates",
        "Observable_UseObservable_SourceSwap",
        // PropertyGrid
        "PropertyGrid_Reflection_MutableObject",
        "PropertyGrid_Reflection_Categorized",
        "PropertyGrid_Reflection_EnumEditor",
        "PropertyGrid_Nested_ImmutableRecord",
        "PropertyGrid_Immutable_Root",
        "PropertyGrid_Custom_Editor",
        "PropertyGrid_Target_Switching",
        "PropertyGrid_Category_ExpandCollapse",
        "PropertyGrid_DeepNesting_RecordInRecord",
        "PropertyGrid_INPC_ExternalMutation",
        // Localization
        "Localization_LocaleSwitching",
        // TypeRegistration mismatch regression
        "Reconciler_TypeMismatch_UpdateFallback",
        "Reconciler_TypeMismatch_UnmountSkip",
        // Control catalog — mount/unmount every control type
        "ControlCatalog_MountUnmountAll",
        // Reconciler stress tests — target uncovered branches
        "ReconcilerStress_KeyedSuffixMatch",
        "ReconcilerStress_KeyedMiddleRemoval",
        "ReconcilerStress_KeyedComplexReorder",
        "ReconcilerStress_KeyedInsertRemoveReorder",
        "ReconcilerStress_PositionalTypeMismatch",
        "ReconcilerStress_FuncElementRerender",
        "ReconcilerStress_ElementToNullTransition",
        "ReconcilerStress_ComponentUnmountCleanup",
        "ReconcilerStress_NestedContainerUnmount",
        "ReconcilerStress_KeyedLargeListStress",
        "ReconcilerStress_MultiCycleReconcile",
        "ReconcilerStress_KeyedPrefixTypeBreak",
        // Control update tests — exercise UpdateXxx dispatch + ApplyModifiers
        "ControlUpdate_TextProperty",
        "ControlUpdate_ButtonProperty",
        "ControlUpdate_InputControls",
        "ControlUpdate_DateTimePicker",
        "ControlUpdate_Containers",
        "ControlUpdate_Collections",
        "ControlUpdate_Navigation",
        "ControlUpdate_Modifiers",
        "ControlUpdate_PaddingModifiers",
        "ControlUpdate_Shapes",
        "ControlUpdate_StatusControls",
        "ControlUpdate_Grid",
        "ControlUpdate_ModifiedElementUnwrap",
        "ControlUpdate_HyperlinkButton",
        // Control update tests — wave 2 (remaining UpdateXxx + Mount paths)
        "ControlUpdate2_NavigationView",
        "ControlUpdate2_Image",
        "ControlUpdate2_AdditionalControls",
        "ControlUpdate2_TextBitmaskDiff",
        "ControlUpdate2_LegacyModifiedElement",
        "ControlUpdate2_ButtonVariants",
        "ControlUpdate2_ExpanderContent",
        "ControlUpdate2_VisibilityModifier",
        "ControlUpdate2_RichEditBox",
        "ControlUpdate2_AutoSuggestBox",
        // Modifier and event handler tests
        "ModifierEvent_EventHandlers",
        "ModifierEvent_Brushes",
        "ModifierEvent_Tooltip",
        "ModifierEvent_Automation",
        "ModifierEvent_ImplicitTransitions",
        "ModifierEvent_BorderModifiers",
        "ModifierEvent_OnMountAction",
        // Rare control mount + update tests
        "RareControl_ColorPicker",
        "RareControl_TeachingTip",
        "RareControl_GridView",
        "RareControl_PersonPicture",
        "RareControl_RelativePanel",
        "RareControl_CalendarView",
        "RareControl_RichTextBlock",
        "RareControl_PasswordBox",
        "RareControl_ComboBoxRadioButtons",
        // Component hook tests
        "ComponentHook_UseReducerFunctional",
        "ComponentHook_UseReducerRedux",
        "ComponentHook_UseMemoCallbackRef",
        "ComponentHook_UseEffectWithDeps",
        "ComponentHook_TypedProps",
        "ComponentHook_UseWindowSize",
        "ComponentHook_UseBreakpoint",
        "ComponentHook_MultipleComponents",
        // DSL and extension tests
        "DslExt_FluentModifierChain",
        "DslExt_TransitionExtensions",
        "DslExt_FactoryMethods",
        "DslExt_ShapeExtensions",
        "DslExt_GridBuilders",
        "DslExt_MenuDslMethods",
        "DslExt_AttachedProperties",
        "DslExt_ErrorBoundaryElement",
        "DslExt_GroupElement",
        // Layout animation
        "LayoutAnimation_OffsetSetup",
        "LayoutAnimation_SpringSetup",
        "LayoutAnimation_SizeSetup",
        "ConnectedAnimation_MountUnmount",
        // Thread-safe hook stress tests — real WinUI rendering + background threads
        "ThreadSafe_RapidBackgroundSetState",
        "ThreadSafe_MultipleHooksConcurrent",
        "ThreadSafe_ReducerSerializationStress",
        "ThreadSafe_HighFrequencyLargeTree",
        "ThreadSafe_RenderCoalescing",
    ];

    public static SelfTestFixtureBase? Create(string name, Harness harness) => name switch
    {
        "ErrorBoundary_CatchesRenderError" => new ErrorBoundaryFixtures.CatchesRenderError(harness),
        "ErrorBoundary_Recovery" => new ErrorBoundaryFixtures.Recovery(harness),
        "Reconciler_MountText" => new ReconcilerFixtures.MountText(harness),
        "Reconciler_UpdateText" => new ReconcilerFixtures.UpdateText(harness),
        "Reconciler_AddRemoveChildren" => new ReconcilerFixtures.AddRemoveChildren(harness),
        "Reconciler_ComponentRerender" => new ReconcilerFixtures.ComponentRerender(harness),
        "Reconciler_KeyedList" => new ReconcilerFixtures.KeyedList(harness),
        "Reconciler_GridDynamicChildCount" => new ReconcilerFixtures.GridDynamicChildCount(harness),
        "Reconciler_AllLayoutsDynamicChildCount" => new ReconcilerFixtures.AllLayoutsDynamicChildCount(harness),
        "FlexLayout_RowDistribution" => new LayoutFixtures.FlexRowDistribution(harness),
        "FlexLayout_ColumnWrap" => new LayoutFixtures.FlexColumnWrap(harness),
        "Grid_RowColumnLayout" => new LayoutFixtures.GridRowColumn(harness),
        "GridVsFlex_StarSizing" => new LayoutFixtures.GridVsFlexStarSizing(harness),
        "Flex_NestedRowInColumn" => new FlexLayoutFixtures.FlexNestedRowInColumn(harness),
        "Flex_NestedColumnInRow" => new FlexLayoutFixtures.FlexNestedColumnInRow(harness),
        "Flex_NestedDeep" => new FlexLayoutFixtures.FlexNestedDeep(harness),
        "Flex_InsideGrid" => new FlexLayoutFixtures.FlexInsideGrid(harness),
        "Flex_InsideBorder" => new FlexLayoutFixtures.FlexInsideBorder(harness),
        "Flex_InsideVStack" => new FlexLayoutFixtures.FlexInsideVStack(harness),
        "Flex_InsideScrollView" => new FlexLayoutFixtures.FlexInsideScrollView(harness),
        "Flex_ScrollViewInsideFlex" => new FlexLayoutFixtures.ScrollViewInsideFlex(harness),
        "Flex_ColumnGrow" => new FlexLayoutFixtures.FlexColumnGrow(harness),
        "Flex_MixedGrowFixed" => new FlexLayoutFixtures.FlexMixedGrowFixed(harness),
        "Flex_WithGaps" => new FlexLayoutFixtures.FlexWithGaps(harness),
        "Flex_WithPadding" => new FlexLayoutFixtures.FlexWithPadding(harness),
        "Flex_CrossAxisTextHeight" => new FlexLayoutFixtures.FlexCrossAxisTextHeight(harness),
        "Flex_GridInsideFlex" => new FlexLayoutFixtures.GridInsideFlex(harness),
        "Flex_WithChildMargins" => new FlexLayoutFixtures.FlexWithChildMargins(harness),
        "Flex_JustifySpaceBetween" => new FlexLayoutFixtures.FlexJustifySpaceBetween(harness),
        "Flex_LayoutCycleInGridStar" => new FlexLayoutFixtures.FlexLayoutCycleInGridStar(harness),
        "Flex_LayoutCycleNestedDeep" => new FlexLayoutFixtures.FlexLayoutCycleNestedDeep(harness),
        "Flex_LayoutCycleAutoText" => new FlexLayoutFixtures.FlexLayoutCycleAutoText(harness),
        "Flex_LayoutCycleSizeMismatch" => new FlexLayoutFixtures.FlexLayoutCycleSizeMismatch(harness),
        "DynamicList_GrowShrink" => new DynamicFixtures.ListGrowShrink(harness),
        "ConditionalRendering_Toggle" => new DynamicFixtures.ConditionalToggle(harness),
        "Markdown_HeadingsAndFormatting" => new MarkdownFixtures.HeadingsAndFormatting(harness),
        "Markdown_CodeBlockAndLinks" => new MarkdownFixtures.CodeBlockAndLinks(harness),
        "MonacoEditor_Mounts" => new MonacoFixtures.EditorMounts(harness),
        "D3_LineChart" => new D3Fixtures.LineChart(harness),
        "D3_BarChart" => new D3Fixtures.BarChart(harness),
        "D3_PieChart" => new D3Fixtures.PieChart(harness),
        "ListView_TypedRendering" => new CollectionFixtures.ListViewTyped(harness),
        "Navigation_TabSwitching" => new NavigationFixtures.TabSwitching(harness),
        "Navigation_NavHostRendersInitial" => new NavigationFixtures.NavHostRendersInitial(harness),
        "Navigation_NavHostContentSwap" => new NavigationFixtures.NavHostContentSwap(harness),
        "Navigation_NavHostGoBack" => new NavigationFixtures.NavHostGoBack(harness),
        "Navigation_NavHostLifecycleOrder" => new NavigationFixtures.NavHostLifecycleOrder(harness),
        "Navigation_NavHostNested" => new NavigationFixtures.NavHostNested(harness),
        "Observable_UseObservable_Rerender" => new ObservableFixtures.UseObservable_Rerender(harness),
        "Observable_UseObservable_ExternalMutation" => new ObservableFixtures.UseObservable_ExternalMutation(harness),
        "Observable_UseObservableProperty_FineGrained" => new ObservableFixtures.UseObservableProperty_FineGrained(harness),
        "Observable_UseCollection_ListUpdates" => new ObservableFixtures.UseCollection_ListUpdates(harness),
        "Observable_UseObservable_SourceSwap" => new ObservableFixtures.UseObservable_SourceSwap(harness),
        // PropertyGrid
        "PropertyGrid_Reflection_MutableObject" => new PropertyGridFixtures.Reflection_MutableObject(harness),
        "PropertyGrid_Reflection_Categorized" => new PropertyGridFixtures.Reflection_Categorized(harness),
        "PropertyGrid_Reflection_EnumEditor" => new PropertyGridFixtures.Reflection_EnumEditor(harness),
        "PropertyGrid_Nested_ImmutableRecord" => new PropertyGridFixtures.Nested_ImmutableRecord(harness),
        "PropertyGrid_Immutable_Root" => new PropertyGridFixtures.Immutable_Root(harness),
        "PropertyGrid_Custom_Editor" => new PropertyGridFixtures.Custom_Editor(harness),
        "PropertyGrid_Target_Switching" => new PropertyGridFixtures.Target_Switching(harness),
        "PropertyGrid_Category_ExpandCollapse" => new PropertyGridFixtures.Category_ExpandCollapse(harness),
        "PropertyGrid_DeepNesting_RecordInRecord" => new PropertyGridFixtures.DeepNesting_RecordInRecord(harness),
        "PropertyGrid_INPC_ExternalMutation" => new PropertyGridFixtures.INPC_ExternalMutation(harness),
        // Localization
        "Localization_LocaleSwitching" => new LocalizationFixtures.LocaleSwitching(harness),
        // TypeRegistration mismatch regression
        "Reconciler_TypeMismatch_UpdateFallback" => new TypeRegistrationMismatchFixtures.UpdateControlTypeMismatch(harness),
        "Reconciler_TypeMismatch_UnmountSkip" => new TypeRegistrationMismatchFixtures.UnmountControlTypeMismatch(harness),
        // Control catalog
        "ControlCatalog_MountUnmountAll" => new ControlCatalogFixtures.MountUnmountAllControls(harness),
        // Reconciler stress tests
        "ReconcilerStress_KeyedSuffixMatch" => new ReconcilerStressFixtures.KeyedSuffixMatch(harness),
        "ReconcilerStress_KeyedMiddleRemoval" => new ReconcilerStressFixtures.KeyedMiddleRemoval(harness),
        "ReconcilerStress_KeyedComplexReorder" => new ReconcilerStressFixtures.KeyedComplexReorder(harness),
        "ReconcilerStress_KeyedInsertRemoveReorder" => new ReconcilerStressFixtures.KeyedInsertRemoveReorder(harness),
        "ReconcilerStress_PositionalTypeMismatch" => new ReconcilerStressFixtures.PositionalTypeMismatch(harness),
        "ReconcilerStress_FuncElementRerender" => new ReconcilerStressFixtures.FuncElementRerender(harness),
        "ReconcilerStress_ElementToNullTransition" => new ReconcilerStressFixtures.ElementToNullTransition(harness),
        "ReconcilerStress_ComponentUnmountCleanup" => new ReconcilerStressFixtures.ComponentUnmountCleanup(harness),
        "ReconcilerStress_NestedContainerUnmount" => new ReconcilerStressFixtures.NestedContainerUnmount(harness),
        "ReconcilerStress_KeyedLargeListStress" => new ReconcilerStressFixtures.KeyedLargeListStress(harness),
        "ReconcilerStress_MultiCycleReconcile" => new ReconcilerStressFixtures.MultiCycleReconcile(harness),
        "ReconcilerStress_KeyedPrefixTypeBreak" => new ReconcilerStressFixtures.KeyedPrefixTypeBreak(harness),
        // Control update tests
        "ControlUpdate_TextProperty" => new ControlUpdateFixtures.TextPropertyUpdate(harness),
        "ControlUpdate_ButtonProperty" => new ControlUpdateFixtures.ButtonPropertyUpdate(harness),
        "ControlUpdate_InputControls" => new ControlUpdateFixtures.InputControlsUpdate(harness),
        "ControlUpdate_DateTimePicker" => new ControlUpdateFixtures.DateTimePickerUpdate(harness),
        "ControlUpdate_Containers" => new ControlUpdateFixtures.ContainerUpdate(harness),
        "ControlUpdate_Collections" => new ControlUpdateFixtures.CollectionUpdate(harness),
        "ControlUpdate_Navigation" => new ControlUpdateFixtures.NavigationUpdate(harness),
        "ControlUpdate_Modifiers" => new ControlUpdateFixtures.ModifierUpdate(harness),
        "ControlUpdate_PaddingModifiers" => new ControlUpdateFixtures.PaddingModifierUpdate(harness),
        "ControlUpdate_Shapes" => new ControlUpdateFixtures.ShapeUpdate(harness),
        "ControlUpdate_StatusControls" => new ControlUpdateFixtures.StatusControlUpdate(harness),
        "ControlUpdate_Grid" => new ControlUpdateFixtures.GridUpdate(harness),
        "ControlUpdate_ModifiedElementUnwrap" => new ControlUpdateFixtures.ModifiedElementUnwrap(harness),
        "ControlUpdate_HyperlinkButton" => new ControlUpdateFixtures.HyperlinkButtonUpdate(harness),
        // Control update tests — wave 2
        "ControlUpdate2_NavigationView" => new ControlUpdateFixtures2.NavigationViewUpdate(harness),
        "ControlUpdate2_Image" => new ControlUpdateFixtures2.ImageUpdate(harness),
        "ControlUpdate2_AdditionalControls" => new ControlUpdateFixtures2.AdditionalControlsMountUpdate(harness),
        "ControlUpdate2_TextBitmaskDiff" => new ControlUpdateFixtures2.TextBitmaskDiffUpdate(harness),
        "ControlUpdate2_LegacyModifiedElement" => new ControlUpdateFixtures2.LegacyModifiedElementUpdate(harness),
        "ControlUpdate2_ButtonVariants" => new ControlUpdateFixtures2.ButtonVariantsUpdate(harness),
        "ControlUpdate2_ExpanderContent" => new ControlUpdateFixtures2.ExpanderContentUpdate(harness),
        "ControlUpdate2_VisibilityModifier" => new ControlUpdateFixtures2.VisibilityModifier(harness),
        "ControlUpdate2_RichEditBox" => new ControlUpdateFixtures2.RichEditBoxUpdate(harness),
        "ControlUpdate2_AutoSuggestBox" => new ControlUpdateFixtures2.AutoSuggestBoxUpdate(harness),
        // Modifier and event handler tests
        "ModifierEvent_EventHandlers" => new ModifierEventFixtures.EventHandlerModifiers(harness),
        "ModifierEvent_Brushes" => new ModifierEventFixtures.BrushModifiers(harness),
        "ModifierEvent_Tooltip" => new ModifierEventFixtures.TooltipModifier(harness),
        "ModifierEvent_Automation" => new ModifierEventFixtures.AutomationModifiers(harness),
        "ModifierEvent_ImplicitTransitions" => new ModifierEventFixtures.ImplicitTransitionModifier(harness),
        "ModifierEvent_BorderModifiers" => new ModifierEventFixtures.BorderModifiers(harness),
        "ModifierEvent_OnMountAction" => new ModifierEventFixtures.OnMountActionModifier(harness),
        // Rare control tests
        "RareControl_ColorPicker" => new RareControlFixtures.ColorPickerMountUpdate(harness),
        "RareControl_TeachingTip" => new RareControlFixtures.TeachingTipMount(harness),
        "RareControl_GridView" => new RareControlFixtures.GridViewMountUpdate(harness),
        "RareControl_PersonPicture" => new RareControlFixtures.PersonPictureUpdate(harness),
        "RareControl_RelativePanel" => new RareControlFixtures.RelativePanelMount(harness),
        "RareControl_CalendarView" => new RareControlFixtures.CalendarViewMountUpdate(harness),
        "RareControl_RichTextBlock" => new RareControlFixtures.RichTextBlockUpdate(harness),
        "RareControl_PasswordBox" => new RareControlFixtures.PasswordBoxUpdate(harness),
        "RareControl_ComboBoxRadioButtons" => new RareControlFixtures.ComboBoxRadioButtonsUpdate(harness),
        // Component hook tests
        "ComponentHook_UseReducerFunctional" => new ComponentHookFixtures.UseReducerFunctional(harness),
        "ComponentHook_UseReducerRedux" => new ComponentHookFixtures.UseReducerRedux(harness),
        "ComponentHook_UseMemoCallbackRef" => new ComponentHookFixtures.UseMemoCallbackRef(harness),
        "ComponentHook_UseEffectWithDeps" => new ComponentHookFixtures.UseEffectWithDeps(harness),
        "ComponentHook_TypedProps" => new ComponentHookFixtures.TypedPropsComponent(harness),
        "ComponentHook_UseWindowSize" => new ComponentHookFixtures.UseWindowSizeHook(harness),
        "ComponentHook_UseBreakpoint" => new ComponentHookFixtures.UseBreakpointHook(harness),
        "ComponentHook_MultipleComponents" => new ComponentHookFixtures.MultipleComponents(harness),
        // DSL and extension tests
        "DslExt_FluentModifierChain" => new DslExtensionFixtures.FluentModifierChain(harness),
        "DslExt_TransitionExtensions" => new DslExtensionFixtures.TransitionExtensions(harness),
        "DslExt_FactoryMethods" => new DslExtensionFixtures.DslFactoryMethods(harness),
        "DslExt_ShapeExtensions" => new DslExtensionFixtures.ShapeExtensions(harness),
        "DslExt_GridBuilders" => new DslExtensionFixtures.GridBuilders(harness),
        "DslExt_MenuDslMethods" => new DslExtensionFixtures.MenuDslMethods(harness),
        "DslExt_AttachedProperties" => new DslExtensionFixtures.AttachedProperties(harness),
        "DslExt_ErrorBoundaryElement" => new DslExtensionFixtures.ErrorBoundaryTest(harness),
        "DslExt_GroupElement" => new DslExtensionFixtures.GroupElementTest(harness),
        // Layout animation
        "LayoutAnimation_OffsetSetup" => new LayoutAnimationFixtures.OffsetAnimationSetup(harness),
        "LayoutAnimation_SpringSetup" => new LayoutAnimationFixtures.SpringAnimationSetup(harness),
        "LayoutAnimation_SizeSetup" => new LayoutAnimationFixtures.SizeAnimationSetup(harness),
        "ConnectedAnimation_MountUnmount" => new LayoutAnimationFixtures.ConnectedAnimationMountUnmount(harness),
        // Thread-safe hook stress tests
        "ThreadSafe_RapidBackgroundSetState" => new ThreadSafeHookFixtures.RapidBackgroundSetState(harness),
        "ThreadSafe_MultipleHooksConcurrent" => new ThreadSafeHookFixtures.MultipleHooksConcurrent(harness),
        "ThreadSafe_ReducerSerializationStress" => new ThreadSafeHookFixtures.ReducerSerializationStress(harness),
        "ThreadSafe_HighFrequencyLargeTree" => new ThreadSafeHookFixtures.HighFrequencyLargeTree(harness),
        "ThreadSafe_RenderCoalescing" => new ThreadSafeHookFixtures.RenderCoalescing(harness),
        _ => null,
    };
}
