using Duct.AppTests.Host.SelfTest.Fixtures;

namespace Duct.AppTests.Host.SelfTest;

/// <summary>
/// Maps fixture names to their self-test implementations (the ones with assertions).
/// </summary>
internal static class SelfTestFixtureRegistry
{
    public static readonly string[] AllFixtures =
    [
        "ErrorBoundary_CatchesRenderError",
        "ErrorBoundary_Recovery",
        "Reconciler_MountText",
        "Reconciler_UpdateText",
        "Reconciler_AddRemoveChildren",
        "Reconciler_ComponentRerender",
        "Reconciler_KeyedList",
        "Reconciler_GridDynamicChildCount",
        "Reconciler_AllLayoutsDynamicChildCount",
        "FlexLayout_RowDistribution",
        "FlexLayout_ColumnWrap",
        "Grid_RowColumnLayout",
        "GridVsFlex_StarSizing",
        "Flex_NestedRowInColumn",
        "Flex_NestedColumnInRow",
        "Flex_NestedDeep",
        "Flex_InsideGrid",
        "Flex_InsideBorder",
        "Flex_InsideVStack",
        "Flex_InsideScrollView",
        "Flex_ScrollViewInsideFlex",
        "Flex_ColumnGrow",
        "Flex_MixedGrowFixed",
        "Flex_WithGaps",
        "Flex_WithPadding",
        "Flex_CrossAxisTextHeight",
        "Flex_GridInsideFlex",
        "Flex_WithChildMargins",
        "Flex_JustifySpaceBetween",
        "Flex_LayoutCycleInGridStar",
        "Flex_LayoutCycleNestedDeep",
        "Flex_LayoutCycleAutoText",
        "Flex_LayoutCycleSizeMismatch",
        "DynamicList_GrowShrink",
        "ConditionalRendering_Toggle",
        "Markdown_HeadingsAndFormatting",
        "Markdown_CodeBlockAndLinks",
        "MonacoEditor_Mounts",
        "D3_LineChart",
        "D3_BarChart",
        "D3_PieChart",
        "ListView_TypedRendering",
        "Navigation_TabSwitching",
        "Observable_UseObservable_Rerender",
        "Observable_UseObservable_ExternalMutation",
        "Observable_UseObservableProperty_FineGrained",
        "Observable_UseCollection_ListUpdates",
        "Observable_UseObservable_SourceSwap",
        // PropertyGrid
        "PropertyGrid_Reflection_MutableObject",
        "PropertyGrid_Reflection_Categorized",
        "PropertyGrid_Reflection_EnumEditor",
        "PropertyGrid_Nested_ImmutableRecord",
        "PropertyGrid_Immutable_Root",
        "PropertyGrid_Custom_Editor",
        "PropertyGrid_Target_Switching",
        "PropertyGrid_Category_ExpandCollapse",
        "PropertyGrid_DeepNesting_RecordInRecord",
        "PropertyGrid_INPC_ExternalMutation",
        // Localization
        "Localization_LocaleSwitching",
        // TypeRegistration mismatch regression
        "Reconciler_TypeMismatch_UpdateFallback",
        "Reconciler_TypeMismatch_UnmountSkip",
    ];

    public static SelfTestFixtureBase? Create(string name, Harness harness) => name switch
    {
        "ErrorBoundary_CatchesRenderError" => new ErrorBoundaryFixtures.CatchesRenderError(harness),
        "ErrorBoundary_Recovery" => new ErrorBoundaryFixtures.Recovery(harness),
        "Reconciler_MountText" => new ReconcilerFixtures.MountText(harness),
        "Reconciler_UpdateText" => new ReconcilerFixtures.UpdateText(harness),
        "Reconciler_AddRemoveChildren" => new ReconcilerFixtures.AddRemoveChildren(harness),
        "Reconciler_ComponentRerender" => new ReconcilerFixtures.ComponentRerender(harness),
        "Reconciler_KeyedList" => new ReconcilerFixtures.KeyedList(harness),
        "Reconciler_GridDynamicChildCount" => new ReconcilerFixtures.GridDynamicChildCount(harness),
        "Reconciler_AllLayoutsDynamicChildCount" => new ReconcilerFixtures.AllLayoutsDynamicChildCount(harness),
        "FlexLayout_RowDistribution" => new LayoutFixtures.FlexRowDistribution(harness),
        "FlexLayout_ColumnWrap" => new LayoutFixtures.FlexColumnWrap(harness),
        "Grid_RowColumnLayout" => new LayoutFixtures.GridRowColumn(harness),
        "GridVsFlex_StarSizing" => new LayoutFixtures.GridVsFlexStarSizing(harness),
        "Flex_NestedRowInColumn" => new FlexLayoutFixtures.FlexNestedRowInColumn(harness),
        "Flex_NestedColumnInRow" => new FlexLayoutFixtures.FlexNestedColumnInRow(harness),
        "Flex_NestedDeep" => new FlexLayoutFixtures.FlexNestedDeep(harness),
        "Flex_InsideGrid" => new FlexLayoutFixtures.FlexInsideGrid(harness),
        "Flex_InsideBorder" => new FlexLayoutFixtures.FlexInsideBorder(harness),
        "Flex_InsideVStack" => new FlexLayoutFixtures.FlexInsideVStack(harness),
        "Flex_InsideScrollView" => new FlexLayoutFixtures.FlexInsideScrollView(harness),
        "Flex_ScrollViewInsideFlex" => new FlexLayoutFixtures.ScrollViewInsideFlex(harness),
        "Flex_ColumnGrow" => new FlexLayoutFixtures.FlexColumnGrow(harness),
        "Flex_MixedGrowFixed" => new FlexLayoutFixtures.FlexMixedGrowFixed(harness),
        "Flex_WithGaps" => new FlexLayoutFixtures.FlexWithGaps(harness),
        "Flex_WithPadding" => new FlexLayoutFixtures.FlexWithPadding(harness),
        "Flex_CrossAxisTextHeight" => new FlexLayoutFixtures.FlexCrossAxisTextHeight(harness),
        "Flex_GridInsideFlex" => new FlexLayoutFixtures.GridInsideFlex(harness),
        "Flex_WithChildMargins" => new FlexLayoutFixtures.FlexWithChildMargins(harness),
        "Flex_JustifySpaceBetween" => new FlexLayoutFixtures.FlexJustifySpaceBetween(harness),
        "Flex_LayoutCycleInGridStar" => new FlexLayoutFixtures.FlexLayoutCycleInGridStar(harness),
        "Flex_LayoutCycleNestedDeep" => new FlexLayoutFixtures.FlexLayoutCycleNestedDeep(harness),
        "Flex_LayoutCycleAutoText" => new FlexLayoutFixtures.FlexLayoutCycleAutoText(harness),
        "Flex_LayoutCycleSizeMismatch" => new FlexLayoutFixtures.FlexLayoutCycleSizeMismatch(harness),
        "DynamicList_GrowShrink" => new DynamicFixtures.ListGrowShrink(harness),
        "ConditionalRendering_Toggle" => new DynamicFixtures.ConditionalToggle(harness),
        "Markdown_HeadingsAndFormatting" => new MarkdownFixtures.HeadingsAndFormatting(harness),
        "Markdown_CodeBlockAndLinks" => new MarkdownFixtures.CodeBlockAndLinks(harness),
        "MonacoEditor_Mounts" => new MonacoFixtures.EditorMounts(harness),
        "D3_LineChart" => new D3Fixtures.LineChart(harness),
        "D3_BarChart" => new D3Fixtures.BarChart(harness),
        "D3_PieChart" => new D3Fixtures.PieChart(harness),
        "ListView_TypedRendering" => new CollectionFixtures.ListViewTyped(harness),
        "Navigation_TabSwitching" => new NavigationFixtures.TabSwitching(harness),
        "Observable_UseObservable_Rerender" => new ObservableFixtures.UseObservable_Rerender(harness),
        "Observable_UseObservable_ExternalMutation" => new ObservableFixtures.UseObservable_ExternalMutation(harness),
        "Observable_UseObservableProperty_FineGrained" => new ObservableFixtures.UseObservableProperty_FineGrained(harness),
        "Observable_UseCollection_ListUpdates" => new ObservableFixtures.UseCollection_ListUpdates(harness),
        "Observable_UseObservable_SourceSwap" => new ObservableFixtures.UseObservable_SourceSwap(harness),
        // PropertyGrid
        "PropertyGrid_Reflection_MutableObject" => new PropertyGridFixtures.Reflection_MutableObject(harness),
        "PropertyGrid_Reflection_Categorized" => new PropertyGridFixtures.Reflection_Categorized(harness),
        "PropertyGrid_Reflection_EnumEditor" => new PropertyGridFixtures.Reflection_EnumEditor(harness),
        "PropertyGrid_Nested_ImmutableRecord" => new PropertyGridFixtures.Nested_ImmutableRecord(harness),
        "PropertyGrid_Immutable_Root" => new PropertyGridFixtures.Immutable_Root(harness),
        "PropertyGrid_Custom_Editor" => new PropertyGridFixtures.Custom_Editor(harness),
        "PropertyGrid_Target_Switching" => new PropertyGridFixtures.Target_Switching(harness),
        "PropertyGrid_Category_ExpandCollapse" => new PropertyGridFixtures.Category_ExpandCollapse(harness),
        "PropertyGrid_DeepNesting_RecordInRecord" => new PropertyGridFixtures.DeepNesting_RecordInRecord(harness),
        "PropertyGrid_INPC_ExternalMutation" => new PropertyGridFixtures.INPC_ExternalMutation(harness),
        // Localization
        "Localization_LocaleSwitching" => new LocalizationFixtures.LocaleSwitching(harness),
        // TypeRegistration mismatch regression
        "Reconciler_TypeMismatch_UpdateFallback" => new TypeRegistrationMismatchFixtures.UpdateControlTypeMismatch(harness),
        "Reconciler_TypeMismatch_UnmountSkip" => new TypeRegistrationMismatchFixtures.UnmountControlTypeMismatch(harness),
        _ => null,
    };
}
